Add read / write functions for pci bus
hpi-bs2-st2020-ninjastorms-network/ninjastorms pull request #15
Opened 2020-06-18 11:07 UTC by felixauringer

You can test the pci write and read functions by inserting the following code in the  `read_mac` method in `e1000.c`:
```
for (uint32_t i = 0; i < 8; i++)
{
  uint8_t read = pci_read8(mem_base_mac + i);
  printf("read8 + %i: 0x%x\n", i, read);
}

for (uint32_t i = 0; i < 8; i++)
{
  uint16_t read = pci_read16(mem_base_mac + i);
  printf("read16 + %i: 0x%x\n", i, read);
}

for (uint32_t i = 0; i < 8; i++)
{
  uint32_t read = pci_read32(mem_base_mac + i);
  printf("read32 + %i: 0x%x\n", i, read);
}

for (uint32_t i = 0; i < 8; i++)
{
  uint64_t read = pci_read64(mem_base_mac + i);
  printf("read64 + %i: 0x%x %x\n", i, (uint32_t) (read >> 32), (uint32_t) read);
}

for (uint32_t i = 0; i < 5; i++)
{
  pci_write8(mem_base_mac + i, 0x11);
  uint64_t read = pci_read64(mem_base_mac);
  printf("write8 + %i: 0x%x %x\n", i, (uint32_t) (read >> 32), (uint32_t) read);
  pci_write64(mem_base_mac, 0x8000325476985452);
}

for (uint32_t i = 0; i < 5; i++)
{
  pci_write16(mem_base_mac + i, 0x1123);
  uint64_t read = pci_read64(mem_base_mac);
  printf("write16 + %i: 0x%x %x\n", i, (uint32_t) (read >> 32), (uint32_t) read);
  pci_write64(mem_base_mac, 0x8000325476985452);
}

for (uint32_t i = 0; i < 5; i++)
{
  pci_write32(mem_base_mac + i, 0x11234567);
  uint64_t read = pci_read64(mem_base_mac);
  printf("write32 + %i: 0x%x %x\n", i, (uint32_t) (read >> 32), (uint32_t) read);
  pci_write64(mem_base_mac, 0x8000325476985452);
}

for (uint32_t i = 0; i < 9; i++)
{
  pci_write64(mem_base_mac + i, 0x1123456789ABCDEF);
  uint64_t lower_read = pci_read64(mem_base_mac);
  uint64_t upper_read = pci_read64(mem_base_mac + 8);
  printf("write64 (lower) + %i: 0x%x %x\n", i, (uint32_t) (lower_read >> 32), (uint32_t) lower_read);
  printf("write64 (upper) + %i: 0x%x %x\n", i, (uint32_t) (upper_read >> 32), (uint32_t) upper_read);
  pci_write64(mem_base_mac, 0x8000325476985452);
}
```

2020-06-18 17:42 UTC, sirkrypt0 requested changes
Nice!

2020-06-18 17:42 UTC, sirkrypt0 commented on kernel/network/e1000.c
>  	        printf(":%x", e1000.mac[i]);
Indentation looks kind of broken

2020-06-22 14:43 UTC, felixauringer commented on kernel/network/e1000.c
>  	        printf(":%x", e1000.mac[i]);
You're right, should be fixed now.

2020-06-22 15:01 UTC, sirkrypt0 approved these changes

2020-06-24 15:26 UTC, shm0sby approved these changes

2020-06-24 15:26 UTC, merged