Implemented error logging functions
hpi-bs2-st2020-ninjastorms-network/ninjastorms pull request #16
Opened 2020-06-18 11:23 UTC by Zumarta

2020-06-18 17:47 UTC, sirkrypt0 requested changes
Like it!

2020-06-18 17:47 UTC, sirkrypt0 commented on .gitignore
> +# ignore statements from from https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore
Oops, thats a `from` too much 
```suggestion
# ignore statements from https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore
```

2020-06-18 17:47 UTC, sirkrypt0 commented on kernel/logger/logger.c
> +  }
I think Andreas' style would be one indent less such that the methods brackets start right at the beginning of the line

2020-06-18 17:47 UTC, sirkrypt0 commented on kernel/logger/logger.c
> +  }
Missing newline here

2020-06-18 17:47 UTC, sirkrypt0 commented on .gitignore
> +.history/
Some missing newline

2020-06-18 17:47 UTC, sirkrypt0 commented on kernel/logger/logger.h
> +  };
I think indentation here would be same as with methods, so one less

2020-06-18 17:55 UTC, sirkrypt0 commented
This does not introduce errno usage right? We might do this in a new issue.

2020-06-24 15:42 UTC, felixauringer requested changes
siehe Anmerkungen

2020-06-24 15:42 UTC, felixauringer commented on kernel/logger/logger.c
> +      {
Hier kann man sich den Block sparen, da nur ein Statement folgt

2020-06-24 15:42 UTC, felixauringer commented on kernel/logger/logger.c
> +      {
siehe Zeile 12

2020-06-24 15:42 UTC, felixauringer commented on kernel/logger/logger.c
> +general_log(uint32_t severity, const char* file, const char* format, ...)
komischer Name

2020-06-24 15:42 UTC, felixauringer commented on kernel/logger/logger.h
> +void general_log(uint32_t severity, const char* file, const char* format, ...);
ebenfalls ein komischer Name

2020-06-24 15:42 UTC, felixauringer commented on kernel/logger/logger.h
> +    "DEBUG",
Einrueckung duerfte nur 2 spaces sein

2020-06-24 15:50 UTC, felixauringer approved these changes

2020-06-24 15:52 UTC, sirkrypt0 approved these changes

2020-06-24 15:53 UTC, merged