Feature/time
hpi-bs2-st2020-ninjastorms-network/ninjastorms pull request #29
Opened 2020-07-30 15:16 UTC by sirkrypt0

2020-07-31 07:32 UTC, sirkrypt0 commented
We should create a user mode library for this and use a system call to get the clock time

https://filippo.io/linux-syscall-table/

2020-07-31 09:38 UTC, felixauringer requested changes
Looks very good!

2020-07-31 09:38 UTC, felixauringer commented on kernel/network/routing.h
>  #define ROUTING_DEBUG
We should comment out this as well

2020-07-31 09:38 UTC, felixauringer commented on kernel/time.c
> +#include <stdio.h>
Where do we need this?

2020-07-31 09:39 UTC, felixauringer commented
> We should create a user mode library for this and use a system call to get the clock time
> 
> https://filippo.io/linux-syscall-table/

Can we please do this after the remaining exams?

2020-08-01 13:09 UTC, felixauringer approved these changes

2020-08-01 13:09 UTC, merged